feat: support for taskfile
stevearc/overseer.nvim pull request #102
Opened 2023-02-15 20:53 UTC by laxtiz

A task runner / simpler Make alternative written in Go

repo: https://github.com/go-task/task
homepage: https://taskfile.dev/

2023-02-16 17:40 UTC, stevearc requested changes
Looks good! Just one question

2023-02-16 17:40 UTC, stevearc commented on lua/overseer/template/task.lua
> +          -- cb(ret)
Any reason these are commented out? It's important for the caller to be alerted when the provider encounters an error.

2023-02-17 03:43 UTC, laxtiz commented on lua/overseer/template/task.lua
> +          -- cb(ret)
ok, i fixed it

2023-02-17 06:13 UTC, stevearc commented
Awesome, thanks for the PR!

2023-02-17 06:13 UTC, merged