feat(summary): Skip [Process exited] in summary
stevearc/overseer.nvim pull request #26
Opened 2022-09-01 06:35 UTC by ranjithshegde

With the latest commit, the Overseer sidebar now displays the helpful
summary of the tast. But for a shell command of c++ compile commands,
the last line is always [Process extied err_code] which is not helpful
because the task exit notification already states if it was success or
failure. This PR just gets the next non_empty line from the bottom

2022-09-01 14:24 UTC, stevearc requested changes
Suggestion for simplification

2022-09-01 14:24 UTC, stevearc commented on lua/overseer/component/on_output_summarize.lua
> +            end
I think this will be simpler if you simply change line 24 (can't comment there, thanks github) to
```lua
  while not vim.tbl_isempty(lines) and (lines[#lines] == "" or lines[#lines]:match("^%[Process exited")) do
```

2022-09-01 18:39 UTC, ranjithshegde commented on lua/overseer/component/on_output_summarize.lua
> +            end
yes that is simpler!
I am on the road for the next 16 hours. Dont want to hold up such a small change. Please feel free to close this if you want to implement it yourself sooner

2022-09-03 00:53 UTC, stevearc commented
Added in b10154a64cd808b351c8ff6ebf7c96926f7dfedf

2022-09-03 00:53 UTC, closed without merging