feat: add config option `task_list → group_position` (#262)
stevearc/overseer.nvim pull request #299
Opened 2024-05-31 14:30 UTC by Zeioth

This PR solve #262.

## Screenshots
* `group_position = "top"`
![screenshot_2024-05-31_16-24-16_281218760](https://github.com/stevearc/overseer.nvim/assets/3357792/3853d683-47f0-44d6-a05e-0518999f43bf)
* `group_position = "bottom"`
![screenshot_2024-05-31_16-24-36_816542893](https://github.com/stevearc/overseer.nvim/assets/3357792/68e07163-bc9a-40c6-b005-7a8d00ca4173)

## Considerations
Defaults should be fine but:
* Please feel free to change the option name if you don't agree with the semantics.
* Please feel free to make it a boolean instead of a string if you prefer.

2024-05-31 14:50 UTC, Zeioth commented
PR coded following the original commit as reference: https://github.com/stevearc/overseer.nvim/commit/6fe36fc338fbeaf35b0f801c25f7f231c431a64b

2024-06-04 06:34 UTC, stevearc requested changes
I don't love this solution because I think it makes it more difficult to tell which task is the parent of the subtasks. As another possible way to solve this, I put together #306. Using this API, you could then make the task output view default to showing the results from the most recent non-orchestrator task:

```lua
require("overseer").setup({
  task_list = {
    default_preview = function(self, tasks, task_under_cursor)
      if task_under_cursor then
        return task_under_cursor
      end
      for _, task in ipairs(tasks) do
        if task.strategy.name ~= "orchestrator" and not task:is_pending() then
          return task
        end
      end
      return tasks[1]
    end,
  },
})
```

You can also use the `overseer.create_view` API to manually create a window that will show the output of tasks, customized how you like. What do you think of this approach?

2024-06-04 13:35 UTC, Zeioth commented
@stevearc It's a tradeoff. It would be very appreciated by the users of [compiler.nvim](https://github.com/Zeioth/compiler.nvim) in order to keep backwards compatibility for this new behavior.

That proposed solution doesn't solve [the issue introduced](https://github.com/Zeioth/compiler.nvim/issues/27).

2024-06-04 17:17 UTC, stevearc commented
@Zeioth okay different plan, what about this [`open_output` component](https://github.com/stevearc/overseer.nvim/pull/306)? Would putting this on the orchestrator subtasks solve the issue?

2024-06-05 12:17 UTC, Zeioth commented
I've read the new api and no. Please test overseer with my 2 PR and compiler.nvim if you can, and the case of use is gonna become obvious.

2024-06-05 17:05 UTC, stevearc commented
@Zeioth are you sure? I tried it out and https://github.com/Zeioth/compiler.nvim/pull/45 seems to work fine for me. If you still have a problem with that, could be give me very specific repro steps so I can make sure I'm seeing what you're seeing?

2024-06-06 11:41 UTC, Zeioth commented
open_output fixes the issue. Closing PR in favor of https://github.com/stevearc/overseer.nvim/issues/310

2024-06-06 11:41 UTC, closed without merging