feat: component to show real-time notification with output summary
stevearc/overseer.nvim pull request #356
Opened 2024-09-21 21:35 UTC by jedrzejboczar

Adds a component that can be used as a replacement to `on_complete_notify`. `on_output_notify` will display a notification with task summary for long running tasks. This is helpful to get quick feedback without opening the overseer taskbar. This new component makes use of [nvim-notify](https://github.com/rcarriga/nvim-notify) to update the existing notification window, so when nvim-notify is not installed it will notify only when the task completes (and will display a one-time warning about nvim-notify).

To replace `on_complete_notify`:
```lua
require('overseer').setup {
    component_aliases = {
        default = {
          { "display_duration", detail_level = 2 },
          "on_output_summarize",
          "on_exit_set_status",
          "on_output_notify", -- replaces on_complete_notify
          { "on_complete_dispose", require_view = { "SUCCESS", "FAILURE" } },
        },
    },
}
```

Example screencast:

https://github.com/user-attachments/assets/1ea1ea42-aa64-476d-979d-5b9185419024

2024-09-21 21:42 UTC, jedrzejboczar commented
Added `trim` parameter which is enabled by default because leading/ending whitespace in a small summary window is just wasting valuable space.

2024-10-06 20:37 UTC, stevearc requested changes
Looks neat! Left some comments, but on board with the component overall.

2024-10-06 20:37 UTC, stevearc commented on lua/overseer/component/on_output_notify.lua
> +-- Requires nvim-notify to modify the last notification window when new output arrives instead of creating new notification.
Let's take this and put it in a `long_desc` field on the component. That will ensure that it gets added to the documentation

2024-10-06 20:37 UTC, stevearc commented on lua/overseer/component/on_output_notify.lua
> +      desc = "Number of lines of output to show when detail > 1",
Remove `when detail > 1` because this doesn't consider the task list detail setting

2024-10-06 20:37 UTC, stevearc commented on lua/overseer/component/on_output_notify.lua
> +      desc = "Minimum duration in milliseconds after which to display the notification",
Not really a minimum, right? This is just the amount of time to delay before showing the notification. Maybe a name like `delay_ms` or `show_after_ms` would make more sense

2024-10-06 20:37 UTC, stevearc commented on lua/overseer/component/on_output_notify.lua
> +    },
based on the description, I'm not sure why anyone would ever want this to be false. It sounds like the false behavior will update the notification with the output every time there is a change in the output, _except_ for after the process completes. Wouldn't that just ensure that the final notification is stale and doesn't show the last line(s) of the task after completed?

2024-10-06 20:37 UTC, stevearc commented on lua/overseer/component/on_output_notify.lua
> +end
This is a lot of tricky logic. Let's try to find a way to share it instead of copying it.

2024-10-06 20:37 UTC, stevearc commented on lua/overseer/component/on_output_notify.lua
> +  desc = "Notify with task output summary for long-running tasks or when completed",
The whole point of this is to leverage nvim-notify; we only support fallback behavior when it is not present. Let's call out `nvim-notify` and be clearer about the intended use case for this component.

2024-10-06 20:37 UTC, stevearc commented on lua/overseer/component/on_output_notify.lua
> +        self.start_time = vim.uv.now()
Overseer does still support Neovim 0.8. Let's do a `local uv = vim.uv or vim.loop` at the top of this file and use that.

2024-10-06 20:37 UTC, stevearc commented on lua/overseer/component/on_output_notify.lua
> +        if not complete and not has_nvim_notify() then
You don't need a separate parameter here; you could just check the task status 
```lua
if task:is_running() and not has_nvim_notify() then
```

2024-10-14 19:06 UTC, jedrzejboczar reviewed
Applied the suggestions. I'm not squashing yet to make review easier.

2024-10-14 19:06 UTC, jedrzejboczar commented on lua/overseer/component/on_output_notify.lua
> +-- Requires nvim-notify to modify the last notification window when new output arrives instead of creating new notification.
Done

2024-10-14 19:06 UTC, jedrzejboczar commented on lua/overseer/component/on_output_notify.lua
> +end
Moved to overseer.util

2024-10-14 19:06 UTC, jedrzejboczar commented on lua/overseer/component/on_output_notify.lua
> +  desc = "Notify with task output summary for long-running tasks or when completed",
Added explicit note about nvim-notify

2024-10-14 19:06 UTC, jedrzejboczar commented on lua/overseer/component/on_output_notify.lua
> +      desc = "Number of lines of output to show when detail > 1",
done

2024-10-14 19:06 UTC, jedrzejboczar commented on lua/overseer/component/on_output_notify.lua
> +        if not complete and not has_nvim_notify() then
done

2024-10-14 19:06 UTC, jedrzejboczar commented on lua/overseer/component/on_output_notify.lua
> +        self.start_time = vim.uv.now()
done

2024-10-14 19:06 UTC, jedrzejboczar commented on lua/overseer/component/on_output_notify.lua
> +      desc = "Minimum duration in milliseconds after which to display the notification",
Changed to delay_ms

2024-10-14 19:06 UTC, jedrzejboczar commented on lua/overseer/component/on_output_notify.lua
> +    },
This doesn't prevent showing the notification after completion, it just configures if the completion notification to shows the last lines of task output. I.e. (with `output_on_complete=false`) during runtime we notify with status (RUNNING) and last output, while on completion we notify with status (e.g. SUCCESS) without output lines.

I changed the description and added `long_desc` so it should now be clearer.

2024-10-16 01:53 UTC, stevearc commented
Awesome, thanks for the PR!

2024-10-16 01:53 UTC, merged