fix toggle task list display
stevearc/overseer.nvim pull request #390
Opened 2024-12-24 18:21 UTC by EasonMo

When toggling display task list, it will only be displayed at the end of a large number of blank lines, and will not correctly display the effect of executing `util.terminal_tail_hack()`. 
![image](https://github.com/user-attachments/assets/792e7cbc-f194-419a-95da-621e36a8ff52)
The reason is that the execution order is wrong. The solution is to delay setting the buffer.

2024-12-24 22:05 UTC, stevearc requested changes
This fix makes me a little nervous because it introduces some possible race conditions (what if the window is invalid? What if the buffer is deleted? What if something else switched this window's buffer?) Could you either find a way to fix it without the defer, or provide some repro steps so that I can investigate it myself?

2024-12-25 00:41 UTC, EasonMo commented
Hi, I was a little careless. Now I have analyzed it carefully. The reason why it cannot be displayed correctly is that when calculating scroll lines, the `SideBar` window has not been generated yet, and `terminal_tail_hack()` has not been successfully executed. Therefore, `TaskView:update()` should be executed after the `SideBar` window is generated, rather than in `TaskView:new()` .What do you think?

2024-12-30 13:52 UTC, EasonMo commented
Are there any updates regarding these questions?

2025-01-03 21:17 UTC, stevearc requested changes
I still don't feel great about the removal of the call to `self:update()` because I don't have a good understanding of the side effects of removing it. Again, if you get me a repro for what you're seeing I can look into it, otherwise the change will need to be either obviously correct and free of unintended side effects, or thoroughly tested to ensure it doesn't cause regressions.

2025-01-03 21:17 UTC, stevearc commented on lua/overseer/component/display_duration.lua
> +        end
The timer is a singleton. When a task is created with this component we initialize this timer so that the task list will get rerendered every second to update the durations on all tasks. If you add this here, after the first task with this component completes, the duration display will only ever get updated when something else rerenders the display. What are you trying to accomplish here?

2025-01-03 23:07 UTC, EasonMo commented
> if you get me a repro for what you're seeing I can look into it

### Describe the bug  

After completing the compilation task for the `.c` file and executing the `OverseerToggle` command, the output window of `tasklist` does not display the initial text information. Instead, it shows a blank space, with the intended text appearing above the empty lines, requiring manual scrolling to view.  

### Steps To Reproduce

1. prepare file

.c file: `test.c`
```c
#include <stdio.h>

void testBase();
void testArray();

int main()
{
    testArray();
    return 0;
}

void testArray()
{
    printf("test array\n");
    int a1[10] = { 1, 2, 3 };
    for (int i = 0; i < 10; i++) {
        printf("%d\n", a[i]);
    }
}
```
nvim config file: 
`lua/overseer/template/user/cpp_build.lua`

```lua
return {
  name = "nvim: gcc build active file",
  builder = function()
    local file = vim.fn.expand("%:.")
    local filetype = vim.fn.expand("%:e")
    local gcc_cmd = "gcc"
    if filetype == "cpp" then
      gcc_cmd = "g++"
    end
    local out = vim.fn.expand("%:r") .. ".out"
    return {
      cmd = { gcc_cmd },
      args = { "-g", file, "-o", out },
      components = {
        "default",
      },
    }
  end,
  condition = {
    filetype = { "c", "cpp" },
  },
}

```

`lua/overseer/template/user/init.lua`
```lua
return { "user.cpp_build", "user.cpp_clean" }
```

config with lazy.vim:
```lua
  {
    "stevearc/overseer.nvim",
    --- @type overseer.Config Configuration options
    opts = {
      templates = {
        "builtin",
        "user",
      },
    },
  },

```

2.  execute `OverseerRun` command, select the `nvim: gcc build active file` item

3. execute `OverseerToggle` command, the result is as shown in the image below:

The output window appears blank.

![image](https://github.com/user-attachments/assets/75d41f1b-e9b4-487d-b8d4-58d8550879e6)

Manual scrolling is required to view the information.

![image](https://github.com/user-attachments/assets/60ef6cae-d2ee-4ecb-9ab8-4b3552d98310)


### Analysis

The cause of this bug, as mentioned earlier, is:

> when calculating scroll lines, the SideBar window has not been generated yet, and terminal_tail_hack() has not been successfully executed. Therefore, TaskView:update() should be executed after the SideBar window is generated, rather than in TaskView:new() .

I don’t believe this will cause any side effects, as events like `OverseerListTaskHover` or `OverseerListFocusChanged` are triggered when displaying the `tasklist` or moving the cursor, which subsequently call `self:update()`. Removing it merely delays the execution.

2025-01-03 23:53 UTC, EasonMo commented on lua/overseer/component/display_duration.lua
> +        end
> The timer is a singleton. When a task is created with this component we initialize this timer so that the task list will get rerendered every second to update the durations on all tasks. If you add this here, after the first task with this component completes, the duration display will only ever get updated when something else rerenders the display. What are you trying to accomplish here?

Could there be some issues with the `display_duration` component? Once all the tasks are completed, the timer should stop working instead of repeatedly calling `task_list.rerender()`. Perhaps you are right; for now, I can’t think of a better solution to ensure it renders correctly.

2025-01-04 00:12 UTC, EasonMo commented on lua/overseer/component/display_duration.lua
> +        end
I think We could add a counter to solve this issue. Since Lua is single-threaded, this should ensure that the count is incremented or decreased correctly.

```lua
local task_list = require("overseer.task_list")
local util = require("overseer.util")

local timer
local count = 0

---@type overseer.ComponentFileDefinition
local comp = {
  desc = "Display the run duration",
  params = {
    detail_level = {
      desc = "Show the duration at this detail level",
      type = "integer",
      default = 1,
      validate = function(v)
        return v >= 1 and v <= 3
      end,
    },
  },
  constructor = function(params)
    return {
      duration = nil,
      start_time = nil,
      on_reset = function(self, task)
        self.duration = nil
        self.start_time = nil
      end,
      on_start = function(self)
        if not timer then
          timer = assert(vim.loop.new_timer())
          timer:start(
            1000,
            1000,
            vim.schedule_wrap(function()
              task_list.rerender()
            end)
          )
        end
        self.start_time = os.time()
        count = count + 1
      end,
      on_complete = function(self)
        self.duration = os.time() - self.start_time
        count = count - 1
        if timer and count == 0 then
          timer:stop()
          timer = nil
        end
      end,
      render = function(self, task, lines, highlights, detail)
        if detail < params.detail_level or (not self.duration and not self.start_time) then
          return
        end
        local duration = self.duration or os.time() - self.start_time
        table.insert(lines, util.format_duration(duration))
      end,
    }
  end,
}

return comp

```

2025-01-04 00:42 UTC, stevearc commented
Hmmm...I am not seeing the same issue. Can you confirm that it happens for you even when using this config file (as `nvim -u repro.lua test.c`)

```lua
-- save as repro.lua
-- run with nvim -u repro.lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "stevearc/overseer.nvim",
    config = function()
      require("overseer").setup()
      require("overseer").register_template({
        name = "nvim: gcc build active file",
        builder = function()
          local file = vim.fn.expand("%:.")
          local filetype = vim.fn.expand("%:e")
          local gcc_cmd = "gcc"
          if filetype == "cpp" then
            gcc_cmd = "g++"
          end
          local out = vim.fn.expand("%:r") .. ".out"
          return {
            cmd = { gcc_cmd },
            args = { "-g", file, "-o", out },
            components = {
              "default",
            },
          }
        end,
        condition = {
          filetype = { "c", "cpp" },
        },
      })
    end,
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
  dev = {
    path = "~/dotfiles/vimplugins",
    patterns = { "stevearc" },
  },
})
```

2025-01-04 01:42 UTC, EasonMo commented
This is quite strange. I couldn’t reproduce the issue using your configuration alone. However, after adding LazyVim, the issue becomes reproducible.
```lua
-- save as repro.lua
-- run with nvim -u repro.lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  {
    "stevearc/overseer.nvim",
    config = function()
      require("overseer").setup()
      require("overseer").register_template({
        name = "nvim: gcc build active file",
        builder = function()
          local file = vim.fn.expand("%:.")
          local filetype = vim.fn.expand("%:e")
          local gcc_cmd = "gcc"
          if filetype == "cpp" then
            gcc_cmd = "g++"
          end
          local out = vim.fn.expand("%:r") .. ".out"
          return {
            cmd = { gcc_cmd },
            args = { "-g", file, "-o", out },
            components = {
              "default",
            },
          }
        end,
        condition = {
          filetype = { "c", "cpp" },
        },
      })
    end,
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
  dev = {
    path = "~/dotfiles/vimplugins",
    patterns = { "stevearc" },
  },
})

```

2025-01-05 05:43 UTC, stevearc commented
Okay, it does repro with LazyVim but that's also not super helpful because there's a _ton_ of code and other plugins in there that could be interfering with overseer. I pushed up 2a2b6fe1e04dec2c2e5b6b4deec2894153002778, which is a pretty safe change and expected to work. The one wrinkle is that with LazyVim it still isn't quite perfect. The cursor scrolls to the correct line, but the viewport is scrolled down further than we would like. Unfortunately, I can't figure out what in the config would be causing that. Anything that touches the window layout or window options could cause this, so it's very difficult to find the culprit. The situation is at least improved now, though.

2025-01-05 09:10 UTC, EasonMo commented
I've received your update, and the issue with the excessive blank lines has been bothering me for weeks. Thank you so much for dedicating your time to fix this, and I really appreciate you creating such a useful plugin!

2025-01-05 09:11 UTC, closed without merging