feat: support for deno's task runner
stevearc/overseer.nvim pull request #78
Opened 2022-12-14 11:06 UTC by kaiuri

Adds support for Deno's built-in task runner #77.

2022-12-14 17:44 UTC, stevearc requested changes
Looks good! Just a couple small nits and StyLua is complaining

2022-12-14 17:44 UTC, stevearc commented on lua/overseer/template/deno.lua
> +    args = { optional = true, type = "list", delimiter = " " },
remove the `optional = true` here

2022-12-14 17:44 UTC, stevearc commented on lua/overseer/template/deno.lua
> +    }
This was a (very slightly) bad pattern that I need to go back and change. Instead of extending the cmd list, just pass `args = params.args` in the return value.

2022-12-14 17:44 UTC, stevearc commented on lua/overseer/template/deno.lua
> +    local bin = "deno"
No point in putting this in a variable. You can just use the `"deno"` string directly where it's needed.

2022-12-14 19:53 UTC, kaiuri commented on lua/overseer/template/deno.lua
> +    args = { optional = true, type = "list", delimiter = " " },
Removed

https://github.com/stevearc/overseer.nvim/blob/aacfe5d0ec8af0716bc8b54343d8f3b7dd73f782/lua/overseer/template/deno.lua#L5-L8

2022-12-14 19:54 UTC, kaiuri commented on lua/overseer/template/deno.lua
> +    }
Done

https://github.com/stevearc/overseer.nvim/blob/aacfe5d0ec8af0716bc8b54343d8f3b7dd73f782/lua/overseer/template/deno.lua#L12-L19

2022-12-14 19:58 UTC, kaiuri commented on lua/overseer/template/deno.lua
> +    local bin = "deno"
Used `"deno"` string directly where it's needed.

https://github.com/stevearc/overseer.nvim/blob/aacfe5d0ec8af0716bc8b54343d8f3b7dd73f782/lua/overseer/template/deno.lua#L51-L54

https://github.com/stevearc/overseer.nvim/blob/aacfe5d0ec8af0716bc8b54343d8f3b7dd73f782/lua/overseer/template/deno.lua#L63

https://github.com/stevearc/overseer.nvim/blob/aacfe5d0ec8af0716bc8b54343d8f3b7dd73f782/lua/overseer/template/deno.lua#L69

2022-12-14 23:53 UTC, stevearc approved these changes
Awesome, thanks for the contribution!

2022-12-14 23:53 UTC, merged

2022-12-15 11:23 UTC, kaiuri commented
thank you for this awesome plugin