introduce rake support
stevearc/overseer.nvim pull request #81
Opened 2022-12-16 21:14 UTC by emmanueltouzery

add ruby rake support

2022-12-17 05:49 UTC, emmanueltouzery commented
hmm, is there a way that the user should be prompted for a task parameter, but that the empty value for the parameter is acceptable? I see that it's possible to define [rake tasks with default parameters](https://stackoverflow.com/questions/31731053/how-can-i-call-a-rake-task-with-default-args-from-the-commad-line), so right now it's not OK that i *require* you to enter a value for the parameter. However if I say optional=true the user is not prompted for parameters at all.
I'd like to achieve the current setup (you are prompted for parameters), while allowing for the user to leave a parameter empty.

I have tried:
```lua
    validate = function(value)
      return true,
    end
```
but it's not invoked, overseer already before that rejects the empty string parameter.

2022-12-17 06:13 UTC, emmanueltouzery commented
nevermind, I got it -- introduced a mandatory subcmd with a default value like you did for the mix support :+1: 

should be all good now.

2022-12-20 23:20 UTC, stevearc requested changes
Thanks for the PR! Left some comments, mostly about using idiomatic lua in a few places.

2022-12-20 23:20 UTC, stevearc commented on lua/overseer/template/rake.lua
> +      end
This means that the tasks will only be available when the cwd of Neovim contains the Rakefile. There's nothing wrong with that, but if you want the tasks to be available even if Neovim is in a subdirectory, then instead of using `files.join` use the `findfile` call like in the `cache_key` function. The makefile task provider does this, for example: https://github.com/stevearc/overseer.nvim/blob/82ed207195b58a73b9f7d013d6eb3c7d78674ac9/lua/overseer/template/make.lua#L104-L106

2022-12-20 23:20 UTC, stevearc commented on lua/overseer/template/rake.lua
> +      return true
Also add
```lua
if vim.fn.executable("rake") == 0 then
  return false, 'Command "rake" not found'
end
```

2022-12-20 23:20 UTC, stevearc commented on lua/overseer/template/rake.lua
> +            local _, _, task_name, params = string.find(line, "^rake (%S+)(%[%S+%])")
You can get rid of the `_, _,` by replacing `string.find` -> `string.match` (or `line:match()` if it tickles your fancy)

2022-12-20 23:20 UTC, stevearc commented on lua/overseer/template/rake.lua
> +              task_name = task_name_no_params
Simplification:
```lua
task_name = line:match("^rake (%S+)")
```

2022-12-20 23:20 UTC, stevearc commented on lua/overseer/template/rake.lua
> +            table.insert(tasks, { task_name = task_name, args = args, param_names = param_names })
Maybe I'm missing something, but doesn't this have to be wrapped with `if task_name ~= nil`?

2022-12-20 23:20 UTC, stevearc commented on lua/overseer/template/rake.lua
> +              then
The tbl_filter in the if-statement is a little hard to read. What do you think about removing the if-statement, always doing the for-loop, and at the end have a quick
```lua
if p ~= "" then
  p = "[" .. p .. "]"
end
```

2022-12-20 23:20 UTC, stevearc commented on lua/overseer/template/rake.lua
> +            local args = { subcmd = { type = "string", default = task_name } }
I don't see the subcmd parameter being used anywhere. Is that intentional?

2022-12-20 23:20 UTC, stevearc commented on lua/overseer/template/rake.lua
> +                    p = p .. parms[param_name]
The canonical way of doing this is to insert all of the values into a list-like table and then do a `table.concat(pieces, ",")` to join them with commas.

2022-12-20 23:20 UTC, stevearc commented on lua/overseer/template/rake.lua
> +              local cmd = { "rake", task.task_name .. p }
Ah I see. The `task_name` here should either be referencing the subcmd, or the subcmd parameter should be removed since it won't do anything.

2022-12-21 20:23 UTC, emmanueltouzery commented on lua/overseer/template/rake.lua
> +      end
good catch, i set up neovim to have the current folder being the project root so i didn't notice :+1: 
fixed in the second commit

2022-12-21 20:23 UTC, emmanueltouzery commented on lua/overseer/template/rake.lua
> +      return true
fixed in the second commit

2022-12-21 20:23 UTC, emmanueltouzery commented on lua/overseer/template/rake.lua
> +            local _, _, task_name, params = string.find(line, "^rake (%S+)(%[%S+%])")
fixed in the second commit

2022-12-21 20:24 UTC, emmanueltouzery commented on lua/overseer/template/rake.lua
> +              task_name = task_name_no_params
ouch, should have noticed that :(
fixed in the second commit

2022-12-21 20:24 UTC, emmanueltouzery commented on lua/overseer/template/rake.lua
> +            table.insert(tasks, { task_name = task_name, args = args, param_names = param_names })
i mean "it shouldn't happen", but it's safer, you're right --fixed in the second commit

2022-12-21 20:24 UTC, emmanueltouzery commented on lua/overseer/template/rake.lua
> +              then
fixed in the second commit

2022-12-21 20:27 UTC, emmanueltouzery commented on lua/overseer/template/rake.lua
> +            local args = { subcmd = { type = "string", default = task_name } }
so that goes with the other similar comment about subcmd... the reason i added subcmd is not because I need it, but it allows me to have all other parameters be optional. Since I don't know which parameters are mandatory and which have default values and therefore can be left off, I set them all as optional. However if I just do that, then overseer doesn't allow the user to enter parameters -- it just runs the task. So i add this subcmd parameter with a default value, but mandatory, so that the dialog appears to let the user enter the values for the other parameters.

So i don't really need the subcmd, it's really a workaround, from my point of view.

2022-12-21 20:27 UTC, emmanueltouzery commented on lua/overseer/template/rake.lua
> +                    p = p .. parms[param_name]
fixed with the second commit

2022-12-21 20:28 UTC, emmanueltouzery commented on lua/overseer/template/rake.lua
> +              local cmd = { "rake", task.task_name .. p }
yes, i mean the subcmd allows me to handle the optional parameters as explained earlier. I could read from it here and not use the `task_name` field, but it doesn't seem it would achieve much, to me?

2022-12-26 15:00 UTC, stevearc requested changes

2022-12-26 15:00 UTC, stevearc commented on lua/overseer/template/rake.lua
> +                end
Not sure how rake works, but it looks like you're going to need to pass in positional arguments in the same order in which they are defined. If one of them is nil, do you need to insert an empty element or placeholder or something to make sure the number of arguments lines up?

2022-12-26 15:00 UTC, stevearc commented on lua/overseer/template/rake.lua
> +              local cmd = { "rake", task.task_name .. p }
What about if you remove the `subcmd` entirely and change the rest of the parameters to be `optional = false` and `default = ""`? I think that would do what you want.

2022-12-26 19:34 UTC, emmanueltouzery commented on lua/overseer/template/rake.lua
> +              local cmd = { "rake", task.task_name .. p }
yes, that's correct. I took the `subcmd` idea from the `mix.lua` setup. I now removed `subcmd` entirely in the third commit :+1:

2022-12-26 19:57 UTC, emmanueltouzery commented
hmm I just realized that the parameters for a task are stored in a "hash table", indexed by parameter name, which means that the order in which the parameters will be displayed in the dialog are not guaranteed? I've been apparently very lucky so far, because I always got the order I wanted, but now when testing I got the "wrong" order. That won't affect calling the rake command, but this would be unexpected to the user. Is there a way to enforce the order in which the parameters will appear in the rake GUI?

2022-12-26 20:02 UTC, emmanueltouzery commented on lua/overseer/template/rake.lua
> +                end
I actually believe this `if` is not required.. I removed it. All the parameters should be non-nil, especially now that we default to "". And I tested [] and [param1,] with an optional last parameter, and rake worked as expected (picking the default value for that last parameter).

2022-12-27 15:56 UTC, stevearc commented
I just pushed up 0aeba9b873d1ba072e41458f0b35c2e405b072e9, which will allow you to add an "order" field to the parameter config. That should let you determine the order in which the params appear in the UI.

2022-12-28 21:44 UTC, emmanueltouzery commented
thank you, I updated the PR to take advantage of `order`. again, it was more aesthetic, the plugin was still working, but I think it's better, since rake tasks could take for instance parameters such as "source" and "target", and flipping their order could be quite bad.

2022-12-29 21:52 UTC, stevearc approved these changes
Awesome! Thanks for working through all the comments; this is a great contribution!

2022-12-29 21:52 UTC, merged