feat(npm): detect pnpm
stevearc/overseer.nvim pull request #94
Opened 2023-01-31 04:55 UTC by luan

Detect `pnpm` via `pnpm-lock.yaml` similar to how we're doing for `yarn`. Changed the internal interface to expect an executable name instead of just a flip on `use_yarn`. That didn't look to me like an API that was exposed so it seemed safe to remove it.

2023-02-01 08:33 UTC, stevearc requested changes
Thanks for the PR! Would love to add support for more JS build tools. Just a few changes requested

2023-02-01 08:33 UTC, stevearc commented on lua/overseer/template/npm.lua
> -    use_yarn = { optional = true, type = "boolean" },
This param might be in use in people's personal dotfiles. I'd prefer if we kept this as an optional parameter, marked it as deprecated, and gracefully used it to set the `bin` if not present. See [restart_on_save](https://github.com/stevearc/overseer.nvim/blob/cebb263509fa6cb52c63544845a721dd826b3c15/lua/overseer/component/restart_on_save.lua#L7-L14) for an example of how I've handled deprecating params in the past.

2023-02-01 08:33 UTC, stevearc commented on lua/overseer/template/npm.lua
> +    local bin = params.bin and params.bin or "npm"
Just `params.bin or "npm"` is fine

2023-02-01 08:33 UTC, stevearc commented on lua/overseer/template/npm.lua
> +end
The lua `X and Y or Z` construct is sometimes okay to replace a single ternary operation, but for anything more complex I'd prefer it to be split into `if .. elseif`

2023-02-01 08:33 UTC, stevearc commented on lua/overseer/template/npm.lua
> +end
There's a disconnect here. We're checking if any of these binaries exists for the conditional, but then we use `pick_package_manager` above to choose the binary, which may or may not exist. I'm not sure how "bad" it is to run npm on a yarn or pnpm project, but depending on that I'd recommend either:
1. Check if the result of `pick_package_manager()` is executable
2. Change `pick_package_manager()` to be a preference order based on the lockfiles, but then choose the first binary that's executable.

2023-02-01 08:33 UTC, stevearc commented on lua/overseer/template/npm.lua
> +        return false, "No valid package manager found."
Would prefer to keep the error message as specific as we can make it. Either `'Could not find command "npm", "yarn", or "pnpm"'` or if we're just checking for a single binary then list it specifically. It makes the feedback more actionable to the end user.

2023-02-01 08:33 UTC, stevearc commented on lua/overseer/template/vscode/provider/npm.lua
> +      or "npm"
Same comment about using `if...elseif`

Also `files.join` with a single argument is a no-op

2023-02-01 17:25 UTC, luan reviewed
Thanks for the thorough review! Wasn't sure if that `use_yarn` param in the tmpl was public API or just an internal flag. Did a small refactor while applying the requested changes too.

2023-02-01 17:25 UTC, luan commented on lua/overseer/template/npm.lua
> +end
I don't think it's "bad" to run it. But if you're in a project that has a determined package manager and you can tell it by the lockfile we probably want to fail if that particular one isn't installed.

2023-02-01 17:29 UTC, luan commented on lua/overseer/template/npm.lua
> +    if files.exists(files.join(opts.dir, lockfile)) then
note: yeah, if there are multiple lockfiles we'll just arbitrarily pick the first one we find. There's no good heuristic to chose the best one here in that chase.

2023-02-01 17:29 UTC, luan commented on lua/overseer/template/npm.lua
> +        return false, string.format("Could not find command '%s'", package_manager)
I considered adding the `lockfile` used to pick the package manager to this error, but it got a bit messy with the default `npm` (since that doesn't technically require the lockfile to be there at all) so I stepped back. Let me know if you'd like that detail here and I can refactor how the default is chosen to factor that in here.

2023-02-01 17:29 UTC, luan commented on lua/overseer/template/vscode/provider/npm.lua
> +local lockfiles = {
This is repeated, as well as the logic to pick one. I considered creating a small `npm.lua` utils file to encapsulate it, but didn't want to veer out of this small change into a potentially more structural refactor.

2023-02-02 05:10 UTC, stevearc approved these changes
Looks great! Thanks for the PR!

2023-02-02 05:10 UTC, merged